#!/bin/bash
set -e

if [ ! -z "$DEBUG" ] ; then
  env
  set -x
fi

THIS="$0"
args=("$@")
NUMBER_OF_ARGS="$#"

export APPDIR="$(dirname "$(readlink -f "$THIS")")"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

echo "$APPDIR"

export PATH="${APPDIR}:${APPDIR}/usr/sbin:${PATH}"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${APPDIR}/usr/share/:./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:${XDG_DATA_DIRS}"
export GSETTINGS_SCHEMA_DIR="${APPDIR}/usr/share/glib-2.0/schemas:${GSETTINGS_SCHEMA_DIR}"

BIN="$APPDIR/Discord"

if [ -z "$APPIMAGE_EXIT_AFTER_INSTALL" ] ; then
  trap atexit EXIT
fi

isEulaAccepted=1

VERSION=$(cat "$APPDIR"/resources/build_info.json | jq -r .version)
echo "$VERSION"

mkdir -p "$XDG_CONFIG_HOME"/discord/"$VERSION"/modules/

# Adding modules from build to .config
ln -sf "$APPDIR"/modules/*/* "$XDG_CONFIG_HOME"/discord/"$VERSION"/modules/ || true

# Adding installed.json to .config
cat > "$XDG_CONFIG_HOME"/discord/"$VERSION"/modules/installed.json <<EOF
{
  "discord_desktop_core": {"installedVersion": 1},
  "discord_erlpack": {"installedVersion": 1},
  "discord_spellcheck": {"installedVersion": 1},
  "discord_utils": {"installedVersion": 1},
  "discord_voice": {"installedVersion": 1},
  "discord_zstd": {"installedVersion": 1},
  "discord_krisp": {},
  "discord_game_utils": {},
  "discord_rpc": {}
}
EOF

atexit()
{
  if [ "$isEulaAccepted" == 1 ] ; then
    if [ "$NUMBER_OF_ARGS" -eq 0 ] ; then
      exec "$BIN"
    else
      exec "$BIN" "${args[@]}"
    fi
  fi
}
